name: CI - Commits

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build, Test e Cobertura
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório trocar para uma branch específica
      - name: Clonar repositório e alternar para a branch específica
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # 2. Instalar o compilador/interpretador da linguagem
      - name: Instalar compilador/interpretador (Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalar as dependências do seu projeto
      - name: Instalar as dependências do projeto
        run: npm ci --ignore-scripts

      # 4. (se compilada) compilar o projeto
      - name: Compilar o projeto (TypeScript)
        run: npm run build

      # 5. Executar os testes
      - name: Executar os testes
        run: npm test

      # 6. Garantir 90% de cobertura
      - name: Garantir 90% de cobertura mínima
        run: npm run test:coverage
